version: '3.8'

services:
  api:
    build:
      context: .
    image: forex:develop
    container_name: forex_api
    command: sh scripts/start_api.sh
    restart: on-failure
    volumes:
      - .:/code
      - scripts:/code/scripts
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
  cache:
    image: redis:6.2
    container_name: forex_cache
    restart: on-failure
    volumes:
      - redisdata:/var/lib/redis/data
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 10s
      retries: 5
  db:
    image: postgres:12.7
    container_name: forex_db
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=forex
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    healthcheck:
      test: pg_isready -q -d forex -U postgres
      interval: 10s
      timeout: 10s
      retries: 5
  worker:
    build:
      context: .
    image: worker:develop
    container_name: forex_worker
    command: sh scripts/start_worker.sh
    restart: on-failure
    volumes:
      - .:/code
      - scripts:/code/scripts
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

volumes:
  pgdata:
    driver: local
    name: pgdata
  redisdata:
    driver: local
    name: redisdata
  scripts:
    driver: local
    name: scripts
